"------------"
"Hello $(whoami)!"
"------------"
"Your local time is $(Get-Date)"
"Your machine's hostname is $($env:computername) "
"Your IP is $((Get-NetIPAddress -AddressFamily ipv4 -PrefixOrigin DHCP).ipaddress)"
"Your DNS domains are:`n $((Get-Wmiobject Win32_NetworkAdapterConfiguration |? dnsdomain -ne $null).dnsdomain)" 
"============"
